# These are supported funding model platforms

# patreon: panjiachen
# custom: https://panjiachen.github.io/vue-element-admin-site/donate

# patreon: Yupian Lin
custom: https://github.com/FXLP/MyGallery/blob/main/WeChat_Donate.jpg
